# Generated by Django 4.1.7 on 2023-03-30 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('movil', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=15)),
                ('codigo_rfid', models.CharField(max_length=40)),
                ('imagen', models.CharField(max_length=100)),
                ('fecha_registro', models.IntegerField()),
                ('rol', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_baja', models.IntegerField(blank=True, null=True)),
                ('token_sesion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('familia', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('subcategoria', models.CharField(blank=True, max_length=50)),
                ('numero_serie', models.CharField(max_length=30)),
                ('estado_en_almacen', models.CharField(max_length=20)),
                ('fecha_alta', models.IntegerField()),
                ('localizacion', models.CharField(max_length=100)),
                ('fecha_ultima_accion', models.IntegerField()),
                ('codigo_rfid', models.CharField(max_length=40)),
                ('imagen', models.CharField(max_length=100)),
                ('estado_objeto', models.CharField(max_length=20)),
                ('fecha_baja', models.IntegerField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propietario', to='api.persona')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsable', to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=15)),
                ('fecha', models.IntegerField()),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objeto', to='api.objeto')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona', to='api.persona')),
            ],
        ),
    ]
