# Generated by Django 4.1.7 on 2023-04-06 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='fecha_alta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='fecha_ultima_accion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
